[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd web && npm install"]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "bash start.sh"
