[phases.install]
dependsOn = ["setup"]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt", "cd web && npm install"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20", "gcc"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd web && npm run build"]

[start]
cmd = "bash start.sh"
